### PR TITLE
Support multiple directives per upload and ionic (meteoric).

### PR DESCRIPTION
**Pull request by timbrandin**
Hi @TheAncientGoat and @jimmiebtlr, I've completed work on a PR that makes it possible to have multiple directives per uploaded picture/file and added support for the ionic framework (meteoric).

There was an issue with the Autoform 5+ which I've resolved, it didn't allow functions to be passed back in parameters to _afFieldInput_

Basically this patch allows applications to take advantage of todays rich clients and have them do all the work resizing their picture and upload it s3 through a directive.

**Here's what's done:**
- [x] Support for multiple directives (aka multiple resizes per upload).

``` js
picture: {
  // This package can also take type: [String],
  // but in that case it will only save the src in the order you specified in the directives.
  type: [Object],
  label: 'Select Picture', // (optional, defaults to "Select")
  optional: true, // (optional)
  autoform: {
    type: 'slingshotFileUpload', // (required)
    removeLabel: 'Remove', // (optional, defaults to "Remove")
    afFormGroup: { // (optional)
      label: false
    },
    afFieldInput: {
      // Specify which directive to present as thumbnail using the key.
      thumbnail: 'mobile',
      slingshotdirective: {
        mobile: { // This is the key for the "mobile" version.
          directive: "myMobileDirective",
          onBeforeUpload: function(file, callback) {
            // Create a mobile 640x640 size version.
            Resizer.resize(file, {width: 640, height: 640, cropSquare: true}, function(err, file) {
              if( err ){
                console.error( err );
              }
              callback( file );
            });
          }
        },
        large: { // This is the key for the "large" version.
          directive: "myLargeDirective",
          onBeforeUpload: function(file, callback) {
            // Create a large 1500x1500 size version.
            Resizer.resize(file, {width: 1500, height: 1500, cropSquare: false}, function(err, file) {
              if( err ){
                console.error( err );
              }
              callback( file );
            });
          }
        },
        original: "myOriginalDirective"
      }
    }
  }
},
// NOTICE! These are required if using type: [Object]
'picture.$.key': { type: String },
'picture.$.filename': { type: String },
'picture.$.src': { type: String },
'picture.$.directive': { type: String }
```
- [x] Upgraded to autoform 5.3.0
- [x] Added support for Ionic (Meteoric)
- [x] Store multiple when type: [String].

``` js
picture: [
  "http://s3...",
  "http://s3...",
  "http://s3..."
]
```
- [x] Store multiple when type: [Object].

``` js
picture: [
  {
    key: "mobile",
    filename: "Image1.png",
    directive: "myMobileDirective",
    src: "http://s3..."
  },
  {
    key: "large",
    filename: "Image1.png",
    directive: "myLargeDirective",
    src: "http://s3..."
  },
  {
    key: "original",
    filename: "Image1.png",
    directive: "myOriginalDirective",
    src: "http://s3..."
  }
]
```
- [x] Support Simple Object form (See example resized picture in readme).

``` js
slingshotdirective: {
  directive: 'myDefinedDirective',
  onBeforeUpload: function(files, callback) {
    _.each( files, function(file){
      Resizer.resize(file, {width: 1020, height: 1020, cropSquare: true}, function(err, file) {
        if( err ){
          console.error( err );
          callback( file );
        }else{
          callback( file );
        }
      });
    });
  }
}
```
- [x] Clear files from cache when saved.
- [x] Load saved files from String into the form.
- [x] Load saved files from [String] or [Object] into the form.
- [x] Check so that editing file works.
- [x] Click the file should open an action sheet on ionic (Meteoric)
- [x] Clean up
- [x] Code review (@TheAncientGoat or @jimmiebtlr)

I hope your willing to steer me in the right direction here and that you like the effort.

Cheers,
// Tim

### CODE REVIEW

**Comment by timbrandin** [comment]
Another thing I've added is asynchronous uploads and preview of the image from the blob.

**Comment by timbrandin** [comment]
I think this is ready now for review. What do you guys think? @TheAncientGoat or @jimmiebtlr

**Comment by ryanswrt** [comment]
Great work @timbrandin - reviewing now

**Comment by ryanswrt** [comment]
Slight issue when you have multiple resize directives that use the same slingshot directive - it's better practice to have multiple upload directives I guess, just have to make a note of that somewhere.

Otherwise it works fine for my setup, good job!

Next steps would be to add manual cropping support - as provided by https://github.com/pfafman/meteor-photo-up/

**Comment by timbrandin** [comment]
Cool Yeah, and a progress loader (or atleast some way of securing things get uploaded) did you notice all of that happens in the background now?

What you see is a preview using the blob returned from the Resize package.

Maybe we should either wait for all of it to upload with a progress indicator or let it happen in the background.

What do you think?

Skickat från min iPhone

**Comment by ryanswrt** [comment]
I'll merge this and then track other features as issues for clarity

**Comment by timbrandin** [comment]
Nice! :+1:

**Pull request merged**
